networks:
  webapp_preprod:

services:
  backend:
    container_name: ny_lapako_backend
    build:
      context: .
      target: backend
    volumes:
      - uploads:/app/uploads
    environment:
      - JWT_SECRET=votre_secret_tres_sur_a_changer_en_production
    restart: unless-stopped
    networks:
      - webapp_preprod

  frontend:
    container_name: ny_lapako_frontend
    build:
      context: .
      target: frontend-nginx
      args:
        VITE_API_BASE_URL: http://backend:3000
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - webapp_preprod

volumes:
  uploads:
